INSERT INTO movies(name, date, synopsis) VALUES
    ("TRON", 1982, "A man gets trapped in a computer world!"),
    ("Blade Runner", 1982, "A dystopian future where synthetic humans known as replicants are bio-engineered."),
    ("E.T. the Extra-Terrestrial", 1982, "A young boy befriends an extraterrestrial stranded on Earth."),
    ("The Terminator", 1984, "A cyborg assassin is sent back in time to kill the mother of the future leader of a human resistance."),
    ("Back to the Future", 1985, "A teenager travels back in time with the help of a time machine built by a mad scientist."),
    ("The Breakfast Club", 1985, "Five high school students with different backgrounds spend a Saturday in detention."),
    ("Top Gun", 1986, "A hotshot fighter pilot undergoes training at the Navy's elite fighter weapons school."),
    ("Die Hard", 1988, "A New York cop battles terrorists who have taken hostages in a Los Angeles skyscraper."),
    ("Indiana Jones and the Last Crusade", 1989, "Indiana Jones sets out to find his father and the Holy Grail."),
    ("The Matrix", 1999, "A computer hacker learns about the true nature of reality and his role in the war against its controllers."),
    ("Gladiator", 2000, "A betrayed Roman general seeks justice and revenge."),
    ("The Lord of the Rings: The Fellowship of the Ring", 2001, "A hobbit and his companions set out to destroy a powerful ring to prevent its use by the dark lord."),
    ("Spider-Man", 2002, "A high school student gains spider-like abilities and uses them to fight crime."),
    ("The Dark Knight", 2008, "Batman faces the Joker, a criminal mastermind with a chaotic agenda."),
    ("Avatar", 2009, "A paraplegic marine is sent to the moon Pandora on a unique mission and becomes torn between following orders and protecting an alien civilization."),
    ("Inception", 2010, "A thief who enters others' dreams to steal their secrets is offered a chance to have his criminal history erased."),
    ("The Social Network", 2010, "A biographical drama about the founding of Facebook."),
    ("The Avengers", 2012, "Earth's mightiest heroes must come together to stop an extraterrestrial threat."),
    ("Frozen", 2013, "Two sisters discover the true meaning of love and break a curse of eternal winter."),
    ("Interstellar", 2014, "A group of explorers travels through a wormhole in space in an attempt to ensure humanity's survival."),
    ("Mad Max: Fury Road", 2015, "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland."),
    ("La La Land", 2016, "A jazz musician and an aspiring actress meet and fall in love in Los Angeles."),
    ("Get Out", 2017, "A young African American man uncovers disturbing secrets when he meets his white girlfriend's family."),
    ("Black Panther", 2018, "T'Challa, the king of Wakanda, rises to the throne and faces challenges to his leadership."),
    ("Parasite", 2019, "A poor family schemes to become employed by a wealthy family, with unexpected consequences."),
    ("1917", 2019, "Two British soldiers are tasked with delivering a crucial message during World War I."),
    ("Tenet", 2020, "A protagonist embarks on a mission that involves time manipulation."),
    ("Soul", 2020, "A musician's soul separates from his body, leading him on a journey in the afterlife."),
    ("Nomadland", 2020, "A woman in her 60s, after the economic collapse of a company town, becomes a modern-day nomad."),
    ("Dune", 2021, "Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis and its valuable spice melange.");